### ISSUE TITLE
Broken link to documentation in readme

### ISSUE THREAD

**Issue by tiziano88** [project-oak/tink-rust#144]
https://project-oak.github.io/tink-rust returns a 404 error

**Comment by daviddrysdale** [comment]
Ah, that didn't get updated with the crate name change &ndash; now needs to be a redirect to https://project-oak.github.io/tink-rust/rust/tink_core/index.html. Thanks for spotting.

**Comment by daviddrysdale** [comment]
Fixed in 9df693f95db3b45769cf5dd074197c455c488cc0
