### ISSUE TITLE
Decryption Error in GcpAEAD tests

### ISSUE THREAD

**Issue by itsdpandey** [project-oak/tink-rust#437]
Hello,

I tried testing gcpkms_example() test from integration_test, and "test_gcpkms_basic_aead()" test from gcp_kms_aead_test with valid gcp key uri and credential data, and it returns decryption error with following message:
"thread 'gcpkms::integration_test::gcpkms_example' panicked at 'called `Result::unwrap()` on an `Err` value: TinkError { msg: "aead::decrypt: decryption failed", src: None }', tests/tests/gcpkms/integration_test.rs"
 This appears to be from aead_factory.rs, line 112.
 
 Is this a known issue? Any suggestion how to solve this?

**Comment by daviddrysdale** [comment]
The `gcpkms/` tests haven't been run for a while (they're awkward to set up).  Nothing has changed in the `tink-gcpkms` code for a couple of years, but it's entirely possible that something in the underlying dependencies/SDKs is now different.

Could you give more details of how (e.g. env vars) and where (local? on a GCP instance?) you're invoking the tests?

**Comment by itsdpandey** [comment]
I wrote my own code for encryption and decryption using google kms service that uses live KMS key uri and credential json file, and while testing it, encryption appeared working but decryption failed with error (`Err` value: TinkError { msg: "aead::decrypt: decryption failed", src: None }') . I then used the same key uri and credential file to test the tink-rust lib gcpkms tests as mentioned above and got same error in these tests. The script file you mentioned seems to be updating the key uri and credential information, however I modified the default value of these variables in "https://github.com/project-oak/tink-rust/blob/main/tests/tests/gcpkms/common.rs" file to the live key uri and credential data, and debug assert check shows the used key uri and credential files in these tests are these new defaults values.

**Comment by itsdpandey** [comment]
Hello, Any pointers on how to resolve this issue?

**Comment by itsdpandey** [comment]
Thank you for the information @kauncoder . This solves the issue. closing this now.
