### ISSUE TITLE
About <<Effective Rust>> book

### ISSUE THREAD

**Issue by lispking** [project-oak/tink-rust#678]
@daviddrysdale David, hello, I couldn't find any other contact information for you, so I had to reach out through an issue. I was wondering if you are the author of <<Effective Rust>>? It's a truly well-written book. I am planning to translate it into Chinese and was hoping to get your permission. If it's convenient for you, could you please open-source the source repository for me? Thank you.

**Comment by daviddrysdale** [comment]
Moved to an email from my personal account (please check spam if it doesn't arrive!)
