### ISSUE TITLE
noncebased::Reader doesn't implement io::Read correctly

### ISSUE THREAD

**Issue by str4d** [project-oak/tink-rust#68]
`impl io::Read for noncebased::Reader` follows a relatively standard pattern:
- Return any remaining decrypted data from the previous chunk.
- Read up to a full next chunk.
- Decrypt the chunk.
- Return decrypted data.

It looks like this was directly ported from the Go implementation of Tink. Unfortunately, Go and Rust have different semantics for their standard I/O libraries; the Go implementation is leveraging guarantees about reader behaviour that Rust does not provide.

## Go impl semantics

The Go implementation calls `io.ReadFull` to read a complete segment, and then returns early if it received an error that is not `io.ErrUnexpectedEOF`:

https://github.com/google/tink/blob/cadf02102a05f74be11f18346851b67cea44709f/go/streamingaead/subtle/noncebased/noncebased.go#L278-L281

After handling any initial offset due to the header, it then proceeds to offset all its reads by 1 byte, using that extra final byte as a "query" to see whether there is another following segment. If no such chunk exists, the `io.ErrUnexpectedEOF` error (that was not previously handled) is used to trigger last-segment handling.

This relies on the following semantics of `io.ReadFull`:
- It returns no error if and only if exactly the requested number of bytes were read.
- If fewer bytes were read, but more than zero, it returns `io.ErrUnexpectedEOF` along with the bytes that _were_ read.

## Rust impl semantics

`noncebased::Reader` currently calls `io::Read::read` on the inner reader:

https://github.com/project-oak/tink-rust/blob/172314ff7ecd6e272555db8c57b8dee61aa0bda1/streaming/src/subtle/noncebased.rs#L354-L360

`io::Read::read` provides [no guarantee](https://doc.rust-lang.org/stable/std/io/trait.Read.html#tymethod.read) that it will fill the provided buffer if the inner reader would have sufficient bytes to do so:

> It is not an error if the returned value `n` is smaller than the buffer size, even when the reader is not at the end of the stream yet. This may happen for example because fewer bytes are actually available right now (e. g. being close to end-of-file) **_or because read() was interrupted by a signal._**

This means that the subsequent logic to check for the presence of the last segment can be incorrectly triggered by partial reads of middle segments, in addition to the last-segment read:

https://github.com/project-oak/tink-rust/blob/172314ff7ecd6e272555db8c57b8dee61aa0bda1/streaming/src/subtle/noncebased.rs#L364-L367

The Rust API that more closely matches `io.ReadFull` is `io::Read::read_exact`, but that [doesn't have the same semantics for partial reads](https://doc.rust-lang.org/stable/std/io/trait.Read.html#method.read_exact):

> If this function encounters an "end of file" before completely filling the buffer, it returns an error of the kind `ErrorKind::UnexpectedEof`. **_The contents of `buf` are unspecified in this case._**

## Fix

The Rust implementation needs to loop on `io::Read::read` until either a full segment has been read (plus the query byte), or the inner reader returns `Ok(0)`. See e.g. [my implementation of `io::Read` for STREAM in `age`](https://github.com/str4d/rage/blob/c5c23d67bb49f5b13e3b89c64ecf91a129ae7f19/age/src/primitives/stream.rs#L446-L458). (I don't currently implement the query-byte strategy, because in `age` all chunks are the same size except possibly the final chunk, so I just handle the last-chunk-is-full case by decrypting twice.)

**Comment by daviddrysdale** [comment]
Thanks for the very thorough explanation!  (I feel a bit silly because I'd wondered about this when I was writing/translating the code, then completely forgot to follow up and check the details.)

I had a quick go at making a `read_full` that's closer to Go semantics in #69 &ndash; WDYT?
